language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davidanwar/docker-react -f Dockerfile.dev .

script:
  - - docker run -e CI=true davidanwar/docker-react npm run test
